name: jpeg_markers
description: Scan JPEG markers in a JPEG file.
version: 1.5.0
repository: https://github.com/mgenware/jpeg_markers

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  mgenware_dart_lints: ^6.5.2
  test: ^1.24.0
