name: jpeg_markers
description: Scan JPEG markers in a JPEG file.
version: 2.6.1
repository: https://github.com/mgenware/jpeg_markers

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  mgenware_dart_lints: ^8.1.0
  test: ^1.24.0
